### ISSUE TITLE
._listRef.forceUpdate is not a function

### ISSUE THREAD

**Issue by bitboxer** [bvaughn/react-window-infinite-loader#12]
I am using your nice little package in a small commercial project. It works perfectly. but sometimes I see a `._listRef.forceUpdate is not a function` in the sentry error logs that I don't understand. Sadly I didn't find a good way to reproduce it yet. Do you have a small idea where it might come from?

**Comment by bvaughn** [comment]
Sounds like you've attached the `ref` prop passed to you to something _other_ than a react-window list or grid. That won't work 😅  I'd check there first.
