### ISSUE TITLE
How to use react-window scrollToItem combined with InfiniteLoader / AutoSizer?

### ISSUE THREAD

**Issue by willemx** [bvaughn/react-window-infinite-loader#13]
I created a component based on react-window, react-window-infinite-loader and react-virtualized-auto-sizer. The component is called DataList and renders a AutoSizer which renders a ListWrapper which renders a InfiniteLoader which renders a FixedSizeList:

```
<DataList ...>
    <AutoSizer ...>
        <ListWrapper ....>
            <InfiniteLoader ...>
                <List ....>
```
All is working very well (thank you for these wonderful libs!), but now in my `DataList` component I need to use the `ScrollTo` and `ScrollToItem` functions of the `FixedSizeList` component.
So I think in my `DataList` component I need to get a `ref` to the `List` component deep down below, but I don't see how I can accomplish that. I noticed in the React dos that there is a feature called `forwardRef`. Should I use that feature? Will this not interfere with the refs that are passed between the `InfiniteLoader` and `FixedSizeList` components?
Is there perhaps an example somewhere on how to do this?

(Sorry if this is the wrong place for such a question. I looked in StackOverflow first, but I could not find anything related to this...)

**Comment by bvaughn** [comment]
`forwardRef` is not meant to help with this sort of use case. I think you're essentially asking about how you can attach your own ref to the list while also attaching the ref passed by `InfiniteLoader`.

Essentially you'll want to use a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) in your component that knows how to attach the ref for both `InfiniteLoader` and `DataList` (or whatever needs the ref).

Hopefully this unblocks you. If it doesn't, create a repro and I could take a quick look and suggest a change.

**Comment by willemx** [comment]
Got it working now.
In case some else stumbles upon this, I replaced:
```
<FixedSizeList
    ref={ref}
    ...
```

by:

```
<FixedSizeList
    ref={el => {
        ref(el)
        setListRef(el)
    }}
    ...
```

where `setListRef` is a function that I pass down as a prop from my `DataList` component.

Thanks for unblocking me!

**Comment by bvaughn** [comment]
Good to hear

**Comment by willsmanley** [comment]
@willemx It would be great if you provided a bit of detail around how you are providing the extra ref using a function and how to inject it into your FixedSizeList.
