### ISSUE TITLE
Is it possible to use this with FixedSizeGrid?

### ISSUE THREAD

**Issue by donysukardi** [bvaughn/react-window-infinite-loader#18]
I'm trying to integrate this with FixedSizeGrid from 'react-window', but to no avail.

Could you give me some direction on how I should approach this?

**Comment by bvaughn** [comment]
Please search previous issues before asking a question. Check out #3.

**Comment by donysukardi** [comment]
Thanks Brian! I should have expanded my search. I just searched for FixedSizeGrid instead.

**Comment by bvaughn** [comment]
No worries 👍
