### ISSUE TITLE
type is invalid --       but got: array.

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-window-infinite-loader#22]
![image](https://user-images.githubusercontent.com/47209029/64087423-8781b780-cd6f-11e9-8fd8-e0b5e3cb4f8c.png)

As above, wrap the returned array of the corresponding map in the List component. But I don't seem to be allowed to do that at the moment

![image](https://user-images.githubusercontent.com/47209029/64087503-f6f7a700-cd6f-11e9-9ee1-f8867877bea5.png)

**Comment by bvaughn** [comment]
Read the react-window documentation. That is not how the component API works.

**Comment by JinJieTan** [comment]
But I still haven't found it. Can you give me a link?

**Comment by JinJieTan** [comment]
![image](https://user-images.githubusercontent.com/47209029/64097130-f70a9d80-cd95-11e9-99bd-85129341f74b.png)
When I use this, how do I pass props to the Row component ？

help me ! thank you

**Comment by bvaughn** [comment]
Did you search anywhere for react-window? It should be easy to find.

https://react-window.now.sh

**Comment by JinJieTan** [comment]
i love you . , thank you !   I'm a big fan of facebook ！！

**Comment by bvaughn** [comment]
😊

**Comment by JinJieTan** [comment]
Our project is very large, similar to Telegram desktop IM application, so it is very suitable to use this library. There may be some questions for you later, thank you!
