### ISSUE TITLE
Document usage of resetloadMoreItemsCache function

### ISSUE THREAD

**Issue by frinyvonnick** [bvaughn/react-window-infinite-loader#23]
Hi @bvaughn,

First of all thank you for your work. 

I experienced an [issue](https://github.com/frinyvonnick/react-simple-infinite-loading/issues/4) using your library. I had to implement an infinite loading list that can be sorted. After change the sort order the component wasn't loading new items anymore. I found out it was caused by the cache. I fixed it by passing a ref and calling `resetloadMoreItemsCache` each time the sort order change.

I think a section in the README with explanations about how to deal with this kind usage would be nice. What do you think of it ? (I can open a PR adding this documentation)

**Comment by bvaughn** [comment]
If you'd like to add a PR for this, sure. Sounds great!
