### ISSUE TITLE
 breaking in IE11 due to Array.prototype.find method

### ISSUE THREAD

**Issue by renzosal** [bvaughn/react-window-infinite-loader#27]
InfiniteLoader.js uses Array.find which is not supported in IE11. Since we only check if it is exists, we can change it use array.some.
https://github.com/bvaughn/react-window-infinite-loader/blob/f01d6eff434537bd2e84d57f2c7ed10724547dd3/src/InfiniteLoader.js#L127

PR included :) https://github.com/bvaughn/react-window-infinite-loader/pull/26

**Comment by bvaughn** [comment]
Published via 1.0.5
