### ISSUE TITLE
Change in behavior once item count reaches certain size

### ISSUE THREAD

**Issue by GabeMedrash** [bvaughn/react-window-infinite-loader#28]
Hi there,

I was playing around with your [Code Sandbox demo](https://codesandbox.io/s/5wqo7z2np4) and found that as I increased the itemCount steadily from 10,000 to 100,000 to 1,000,000 items, the scroll behavior changed. I couldn't find this documented in the README, in a prior issue, or on SO.

Specifically, with smaller lists (less than 1,000,000 items) I found that the scroll bar maintains some sense of the item count. Once we hit 1,000,000 items, however, the scroll bar no longer appears to accurately reflect the size of the list. The use case I'm interested in which this seems to not allow is to be able to scroll immediately to the end of the list.

I've attached a GIF showing this behavior with the Code Sandbox demo, as well as my minor modifications in a fork of the Code Sandbox demo.

![one-million-limit](https://user-images.githubusercontent.com/8576080/66949647-bc8a5680-f00b-11e9-80e6-baf1ecdb23aa.gif)

Reproduction: https://codesandbox.io/s/suspicious-nightingale-u7p3m?fontsize=14 

Thanks for taking a look and for the awesome library!

**Comment by bvaughn** [comment]
Unfortunately this is a browser limitation. See my explanation here:
https://github.com/bvaughn/react-window/issues/108#issuecomment-447489217

**Comment by GabeMedrash** [comment]
Oh--was looking in the wrong repo for prior issues! Thanks for the link. Makes sense.

**Comment by bvaughn** [comment]
No problem!
