### ISSUE TITLE
Is it possible to delay item size calculation while using with VariableSizeList

### ISSUE THREAD

**Issue by alex-mironov** [bvaughn/react-window-infinite-loader#29]
I'd like to use this component with `VariableSizeList`. `VariableSizeList` defines a callback `itemSize` which is supposed to return item size. The thing is I don't know the size of the item till it's loaded. Is it possible to somehow overcome this issue? Would be thankful for any help 🙏

**Comment by bvaughn** [comment]
No. Return a default for your loading-in-progress renderer until your data has loaded, then use the `resetAfterIndex()` method [mentioned in the docs](https://react-window.now.sh/#/api/VariableSizeList) to let it know that it should remeasure for your real data.
