### ISSUE TITLE
Warning: Invalid onItemsRendered signature; please refer to InfiniteLoader documentation.

### ISSUE THREAD

**Issue by ranihorev** [bvaughn/react-window-infinite-loader#30]
Hey,

The pacakge is working great (thanks!), however, I'm seeing this warning:
`Invalid onItemsRendered signature; please refer to InfiniteLoader documentation. 
    in List (created by InfiniteLoader)`

Is it an issue on my end?
Thanks!

```
const CustomScrollbarsVirtualList = React.forwardRef<any, { style: React.CSSProperties }>((props, ref) => {
  return (
    <div
      css={css`
        width: 100%;
        height: ${props.style.height}px;
      `}
    >
      <Scrollbar {...props} />
    </div>
  );
});

<InfiniteLoader isItemLoaded={isItemLoaded} itemCount={items.total} loadMoreItems={loadMoreItems}>
      {({ onItemsRendered, ref }) => (
        <List
          height={height}
          width={width}
          itemCount={items.total}
          itemSize={ROW_HEIGHT}
          onItemsRendered={onItemsRendered}
          itemData={items}
          outerElementType={CustomScrollbarsVirtualList}
          outerRef={outerRef}
          ref={ref}
        >
          {Row}
        </List>
      )}
    </InfiniteLoader>
```

**Comment by bvaughn** [comment]
This is the error message that's logged if the callback doesn't receive the right props:
https://github.com/bvaughn/react-window-infinite-loader/blob/31ad47c75641a1feeae0efe3a4f387b19372b460/src/InfiniteLoader.js#L79-L88

It indicates that you passed it to something unexpected.

Since you didn't specify which version of react-window you're using, I'm not sure if this is expected or not.

**Comment by ranihorev** [comment]
I'm using:
"react-window": "^1.8.1",
"react-window-infinite-loader": "^1.0.3",

Thanks for the quick reply :)

**Comment by bvaughn** [comment]
Sorry bat I'm going to need to see a repro. Those two versions work fine together, assuming you followed the documentation examples. Here's a code sandbox showing them working: https://codesandbox.io/s/5wqo7z2np4

**Comment by ranihorev** [comment]
That's fair. I'll try reproducing it in a sandbox

**Comment by ranihorev** [comment]
Found my bug - The value of the `height` prop of List was `undefined` during the first load. Closing :)
