### ISSUE TITLE
Awkward interface in case List already had ref assigned

### ISSUE THREAD

**Issue by kirill-konshin** [bvaughn/react-window-infinite-loader#33]
Assume `const listRef: any = useRef();` has been set already, so in order to wrap List in InfiniteLoader user has to do something like this:

```
<InfiniteLoader>
  {({onItemsRendered, ref}) => (
    <VariableSizeList
      ref={(() => {
        ref(listRef.current);
        return listRef;
      })()}
      ...
    >
```

It would be great in `ref` could return the passed value.

**Comment by bvaughn** [comment]
I don't think that's a good idea. React ref-setter functions typically have a `void` return type.

**Comment by kirill-konshin** [comment]
What would be a better way then? Pass a list ref directly to InfiniteLoader and skip setRef?

**Comment by bvaughn** [comment]
I don't see this as a problem that needs to be fixed, really. Composing ref-setters isn't super common, but I think this is a reasonable approach given the use case.

**Comment by kirill-konshin** [comment]
Agree. In my case I have to force reset: https://github.com/bvaughn/react-window/issues/6#issuecomment-548897123, that's why I need a ref.

It's not a problem, just the interface looks ugly and I haven't yet came up with something nicer other than this self-invoking function...

**Comment by bvaughn** [comment]
Agreed that composing refs looks a little ugly. I don't think it's unacceptably bad or anything though. :) I kind of think it's better to stick with a standard ref-setter method signature than to make a special case here.

**Comment by kirill-konshin** [comment]
So be it )

**Comment by bvaughn** [comment]
Cool. Well thanks for the discussion! :)

**Comment by kirill-konshin** [comment]
For the record, I came up with a less ugly way to call ref-setter and return the ref, given that ref-setter returns void:

```js
// was
ref={(() => {
  ref(listRef);
  return listRef;
})()} // self-executed function

// better way
ref={ref(listRef) || listRef} // simple or since ref() return void
```
