### ISSUE TITLE
Rows are all messed up after re-rendering the loader

### ISSUE THREAD

**Issue by roelzkie15** [bvaughn/react-window-infinite-loader#35]
Im currently working on a chat application and infinite loader has really been helpful but I came across this issue:

![cache-issue-gif](https://user-images.githubusercontent.com/20513403/69012213-454f3600-09ae-11ea-9ee3-8862d1505fc1.gif)

I believe this is a caching issue where it renders component every time i selected another topic/room and the rows is cluttering when doing so. 

Tried to use [`resetloadMoreItemsCache`](https://github.com/bvaughn/react-window-infinite-loader#advanced-usage) but it doesn't resolve this issue.

The expected behaviour is that the rows are arrange just like the first time it was loaded.

**Comment by bvaughn** [comment]
I can't look at bug reports without a repro. Share a Code Sandbox and I'll take a look?

Make sure you're using the `style` prop btw. Looks like you might not be.

**Comment by roelzkie15** [comment]
Sure, Please leave this ticket open until I posted the code sandbox. 🚀

**Comment by roelzkie15** [comment]
This issue is rather a https://react-window-reversed.now.sh/ so closing this now.
