### ISSUE TITLE
maximumBatchSize attribute

### ISSUE THREAD

**Issue by adacosta** [bvaughn/react-window-infinite-loader#4]
Hello,

I'm curious if there has been any consideration for a maximumBatchSize attribute to split requests. The reason why I ask is, if I scroll quickly, I see large index ranges being requested from my server and I'd like to prevent overly large individual requests. In my use case, I'd like to limit my server query/return at 50 results, maybe with a client side delay between requests. If this attribute isn't desirable, do you have any suggestions for how I might implement a split/limit for my use case? 

Thanks for your time on this project!

**Comment by bvaughn** [comment]
Nope. Not something I've put any thought into.

This isn't a package I use myself for anything. I just published it in case it was helpful to others.

**Comment by bvaughn** [comment]
I'm going to close this issue because I don't plan on taking any action on it. If you'd like to submit a PR, I'm happy to review it 😄 No promises it will get merged though– will depend on the complexity!

Thanks!
