### ISSUE TITLE
where to place `ref`

### ISSUE THREAD

**Issue by SavePointSam** [bvaughn/react-window-infinite-loader#8]
The documentation shows to use ref at the `ref` prop on `FixedSizeList`. However, `FixedSizeList` does not have a `ref` prop, only `outerRef` and `innerRef`. After looking through the source of the packages and inspecting the codesandbox, I believe it's meant to be on `outerRef`. Though, when I do this, I still get an error of `this._listRef.forceUpdate` is not a function.

**Comment by bvaughn** [comment]
`ref` isn't a prop. It's something you attach to a React component like `FixedSizeList`.

Check out the Code Sandbox linked to in the README for example code: https://codesandbox.io/s/x70ly749rq

**Comment by SavePointSam** [comment]
Oh! I didn't realize refs could point to any component instance. I thought it pointed to DOM nodes. Thanks!
